"""table relationships

Revision ID: ad62de65c1a2
Revises: 0d6ea9b81aca
Create Date: 2025-06-26 18:41:44.050453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad62de65c1a2'
down_revision = '0d6ea9b81aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearances', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('episode_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('guest_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearances', schema=None) as batch_op:
        batch_op.alter_column('guest_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('episode_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
